import json
import os
import uuid
from datetime import datetime, timezone

STORAGE_FILE = "citizen_reports.json"

def _load_data():
    if not os.path.exists(STORAGE_FILE):
        return {"reports": []}
    try:
        with open(STORAGE_FILE, "r") as f:
            return json.load(f)
    except Exception:
        return {"reports": []}

def _save_data(data):
    with open(STORAGE_FILE, "w") as f:
        json.dump(data, f, indent=4)

def save_citizen_report(report_dict):
    data = _load_data()
    report_id = f"RPT-{str(uuid.uuid4())[:8].upper()}"
    report_dict["report_id"] = report_id
    # Start immediately as 'submitted' — not stuck in queued state
    report_dict["status"] = "submitted"
    report_dict["timestamp"] = datetime.now(timezone.utc).isoformat()

    # Rich lifecycle metadata
    report_dict.setdefault("priority", "medium")
    report_dict.setdefault("assigned_agency", None)
    report_dict.setdefault("estimated_response_min", None)
    report_dict.setdefault("progress_pct", 10)
    report_dict.setdefault("authority_notes", "")
    report_dict.setdefault("lifecycle_events", [
        {"status": "submitted", "timestamp": report_dict["timestamp"], "note": "Report received by CIRO system"}
    ])

    data["reports"].append(report_dict)
    _save_data(data)
    print(f"[STORAGE] [STEP] Saved citizen report {report_id} — status: submitted")
    return report_id


def get_all_citizen_reports():
    data = _load_data()
    # Return latest first
    return sorted(data["reports"], key=lambda x: x.get("timestamp", ""), reverse=True)

def update_report_status(report_id: str, status: str, metadata: dict = None):
    """Update report status and append lifecycle event."""
    data = _load_data()
    found = False
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc).isoformat()

    # ── 4-stage simplified model (primary stages shown to citizen) ─────────
    status_meta = {
        "submitted":    {"progress_pct": 10,  "assigned_agency": None,              "estimated_response_min": None, "note": "Report received by CIRO system"},
        "under_review": {"progress_pct": 40,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 12,  "note": "AI agents are analysing signals and classifying the incident"},
        "dispatched":   {"progress_pct": 85,  "assigned_agency": "Rescue 1122",     "estimated_response_min": 5,   "note": "Authorities notified. Emergency units dispatched and en route."},
        "resolved":     {"progress_pct": 100, "assigned_agency": "Rescue 1122",     "estimated_response_min": 0,   "note": "Incident resolved by field team"},
        # ── Legacy / internal aliases (kept for backward compatibility) ──────
        "closed":                      {"progress_pct": 100, "assigned_agency": "CIRO AI Command", "estimated_response_min": 0,  "note": "Report closed and archived"},
        "queued_for_analysis":         {"progress_pct": 20,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 15, "note": "Report queued for AI pipeline analysis"},
        "location_verified":           {"progress_pct": 30,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 15, "note": "Incident location and cross-signals verified"},
        "incident_classified":         {"progress_pct": 45,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 12, "note": "AI has classified the incident type"},
        "severity_assessed":           {"progress_pct": 60,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 12, "note": "Incident severity level assessed"},
        "confidence_score_calculated": {"progress_pct": 70,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 10, "note": "Multi-source confidence scored"},
        "resources_identified":        {"progress_pct": 80,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 10, "note": "Optimal emergency resources identified"},
        "response_strategy_generated": {"progress_pct": 85,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 8,  "note": "Response strategy generated by AI"},
        "authorities_notified":        {"progress_pct": 90,  "assigned_agency": "Rescue 1122",     "estimated_response_min": 8,  "note": "Command Center authorities notified"},
        "rescue_units_dispatched":     {"progress_pct": 100, "assigned_agency": "Rescue 1122",     "estimated_response_min": 5,  "note": "Emergency units dispatched and en route"},
        "in_progress":                 {"progress_pct": 100, "assigned_agency": "Rescue 1122",     "estimated_response_min": 3,  "note": "Responders on scene, operation underway"},
        "received":                    {"progress_pct": 5,   "assigned_agency": None,              "estimated_response_min": None,"note": "Report received"},
        "verified":                    {"progress_pct": 35,  "assigned_agency": "CIRO AI Command", "estimated_response_min": 12, "note": "Crisis verified via multi-source signals"},
        "assigned":                    {"progress_pct": 50,  "assigned_agency": "Rescue 1122",     "estimated_response_min": 10, "note": "Field teams assigned to incident"},
        "responding":                  {"progress_pct": 90,  "assigned_agency": "Rescue 1122",     "estimated_response_min": 5,  "note": "Emergency units dispatched"},
    }

    for r in data["reports"]:
        if r.get("report_id") == report_id:
            r["status"] = status
            meta = status_meta.get(status, {})
            r["progress_pct"] = meta.get("progress_pct", r.get("progress_pct", 0))
            if r.get("assigned_agency") is None or meta.get("assigned_agency"):
                r["assigned_agency"] = meta.get("assigned_agency")
            if meta.get("estimated_response_min") is not None:
                r["estimated_response_min"] = meta.get("estimated_response_min")
            if metadata:
                r.update(metadata)
            # Append lifecycle event
            event = {"status": status, "timestamp": now, "note": meta.get("note", "")}
            r.setdefault("lifecycle_events", []).append(event)
            found = True
            print(f"[STORAGE] [STEP] Report {report_id} -> {status} ({meta.get('progress_pct', '?')}%)")
            break

    if found:
        _save_data(data)
    return found

